# This file configures the static analysis results for your project (errors, warnings, and lints).
#
# This enables the lint rules recommended by the Flutter team.
# You can see the full list of supported lints here:
# https://dart.dev/lints
#
# To learn more about customizing static analysis, see the documentation here:
# https://dart.dev/guides/language/analysis-options
include: package:very_good_analysis/analysis_options.yaml

linter:
  # You can temporarily disable rules here, but it is not recommended.
  # rules:
  #   - avoid_print
