name: template_flutter_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Suggested packages for a scalable app
  # go_router: ^14.0.2 # For declarative routing
  # flutter_bloc: ^8.1.5 # For state management
  # get_it: ^7.7.0 # For dependency injection

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Stricter linting rules for higher code quality
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
